### ISSUE TITLE
ValueError: time data 'Mon May 10 23:43:14 2021' does not match format '%a %b  %d %H:%M:%S %Y'

### ISSUE THREAD

**Issue by grobalt** [wolfrage76/windows-plotman#15]
Konnte Plotman interactive 1x starten, er legte auch einen chia prozess an, arbeitet auch an diesem. kurz darauf schließt sich das programm und kann es auch nicht mehr starten:

PS C:\windows-plotman-master> python plotman.py interactive
Traceback (most recent call last):
  File "C:\windows-plotman-master\plotman.py", line 126, in <module>
    interactive.run_interactive()
  File "C:\windows-plotman-master\interactive.py", line 314, in run_interactive
    curses.wrapper(curses_main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\curses\__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "C:\windows-plotman-master\interactive.py", line 108, in curses_main
    jobs = Job.get_running_jobs(dir_cfg['log'])
  File "C:\windows-plotman-master\job.py", line 80, in get_running_jobs
    jobs.append(Job(proc, logroot))
  File "C:\windows-plotman-master\job.py", line 134, in __init__
    self.init_from_logfile()
  File "C:\windows-plotman-master\job.py", line 156, in init_from_logfile
    self.start_time = datetime.strptime(m.group(1), '%a %b  %d %H:%M:%S %Y')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon May 10 23:43:14 2021' does not match format '%a %b  %d %H:%M:%S %Y'
PS C:\windows-plotman-master>

**Comment by grobalt** [comment]
as i am no python developer ... i tried a lot but failed

finally, as a workaround i could change my german windows to use "Englisch (Vereinigte Staaten)" as region format and it works.

are you able to tune this that the local language is supported ? :)

**Comment by berg223** [comment]
Try to just remove this line in [code](https://github.com/wolfrage76/windows-plotman/blob/master/interactive.py#L310).
Tips: locale cause the issue.
