### ISSUE TITLE
"curses function returned NULL" in interactive

### ISSUE THREAD

**Issue by kevklam** [wolfrage76/windows-plotman#18]
This appears to happen when the terminal window is too small. If I start it up and leave it running, eventually when many plots are running in parallel, the dynamic window size calculation tries to create a window too big and runs into this error. Can be worked around by just resizing the terminal to very large before running, but this could cause issues for people not expecting it.

py plotman.py interactive
Traceback (most recent call last):
  File "C:\Users\klam\Desktop\PlotMan\plotman.py", line 126, in <module>
    interactive.run_interactive()
  File "C:\Users\klam\Desktop\PlotMan\interactive.py", line 284, in run_interactive
    curses.wrapper(curses_main)
  File "C:\Users\klam\AppData\Local\Programs\Python\Python39\lib\curses\__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "C:\Users\klam\Desktop\PlotMan\interactive.py", line 230, in curses_main
    dstwin = curses.newwin(
_curses.error: curses function returned NULL

**Comment by aicodex** [comment]
i have forked it, and add "tmpdir_stagger_phase_limit"。
https://gitee.com/xana/windows-plotman/
suggest use
python plotman.py plot
to run
open a new cmd use
python plotman.py status 
to see the status
