### ISSUE TITLE
Problem for amater. Cant start. Get this error. FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Chovus13** [wolfrage76/windows-plotman#6]
First thanks for an effort. It will be nice to work for me, not to put allarm to start a new jobs :-D

I do as instruction you gave.  I installed Python and modules (for the first time). I Copy chia.exe to chia2.exe. Didnt start a GUI version. Make a directories on A: (chia,1,2)....I named NVme drive A:)  and Finally got a "Plotman screen" and then this error:

PS C:\Users\SM\AppData\Local\chia-blockchain\app-1.0.3> python plotman.py interactive
A:\chia\2021-04-13-01.09.23.log
Traceback (most recent call last):
  File "C:\Users\SM\AppData\Local\chia-blockchain\app-1.0.3\plotman.py", line 126, in <module>
    interactive.run_interactive()
  File "C:\Users\SM\AppData\Local\chia-blockchain\app-1.0.3\interactive.py", line 314, in run_interactive
    curses.wrapper(curses_main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\curses\__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "C:\Users\SM\AppData\Local\chia-blockchain\app-1.0.3\interactive.py", line 141, in curses_main
    (started, msg) = manager.maybe_start_new_plot(dir_cfg, sched_cfg, plotting_cfg)
  File "C:\Users\SM\AppData\Local\chia-blockchain\app-1.0.3\manager.py", line 131, in maybe_start_new_plot
    p = subprocess.Popen(plot_args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
PS C:\Users\SM\AppData\Local\chia-blockchain\app-1.0.3>

Where I should look for a problem?

this is my config.yaml

# Where to plot and log.
directories:
        # One directory in which to store all plot job logs (the STDOUT/
        # STDERR of all plot jobs).  In order to monitor progress, plotman
        # reads these logs on a regular basis, so using a fast drive is
        # recommended.
        log: A:\chia

        # One or more directories to use as tmp dirs for plotting.  The
        # scheduler will use all of them and distribute jobs among them.
        # It assumes that IO is independent for each one (i.e., that each
        # one is on a different physical device).
        #
        # If multiple directories share a common prefix, reports will
        # abbreviate and show just the uniquely identifying suffix.
        tmp:
                - a:\1
                - a:\2
                                 

        # Optional: tmp2 directory.  If specified, will be passed to
        # chia plots create as -2.  Only one tmp2 directory is supported.
        # tmp2: /mnt/tmp/a

        # One or more directories; the scheduler will use all of them.
        # These again are presumed to be on independent physical devices,
        # so writes (plot jobs) and reads (archivals) can be scheduled
        # to minimize IO contention.
        dst:
                - h:\
                
                
                            
                
        # Archival configuration.  Optional; if you do not wish to run the
        # archiving operation, comment this section out.
        #
        # Currently archival depends on an rsync daemon running on the remote
        # host, and that the module is configured to match the local path.
        # See code for details.
       # archive:
       #         rsyncd_module: plots
       #         rsyncd_path: /plots
       #         rsyncd_bwlimit: 80000  # Bandwidth limit in KB/s
       #         rsyncd_host: myfarmer
       #         rsyncd_user: chia

# Plotting scheduling parameters
scheduling:
        # Don't run a job on a particular temp dir until all existing jobs
        # have progresed at least this far.  Phase major corresponds to the
        # plot phase, phase minor corresponds to the table or table pair
        # in sequence.
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 1

        # Don't run any jobs (across all temp dirs) more often than this.
        global_stagger_m: 35

        # How often the daemon wakes to consider starting a new plot job
        polling_time_s: 5

# Plotting parameters.  These are pass-through parameters to chia plots create.
# See documentation at
# https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#create
plotting:
        k: 32
        e: False              # Use -e plotting option
        n_threads: 3        # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 5200     # Per job memory

**Comment by Handri-Kosada** [comment]
curses_main error -> try to ALT+Enter (full screen) your powershell / bigger windows.

**Comment by tiagom101** [comment]
I'm getting the same error with this config,

```
directories:
        log: C:\chia_logs
        tmp:
                - d:\1
                - e:\1
        tmp2: C:\chia_tmp
        dst:
                - c:\chia_plot

scheduling:
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 0
        
        tmpdir_max_jobs: 2
        global_stagger_m: 4
        polling_time_s: 1
        
plotting:
        k: 32
        e: False
        n_threads: 12
        n_buckets: 128
        job_buffer: 6000
```

I've checked that all folders exist.

**Comment by tiagom101** [comment]
I fixed this bug by modifying the manager.py to point to the correct chia executable, 

https://github.com/wolfrage76/windows-plotman/blob/master/manager.py#L112

**Comment by elJosho** [comment]
Yea you  may want to mention that in the README until it gets fixed... it's not just looking for chia2.exe, it's looking for a chia2.exe that's hardcoded to use the developer's local user folder.
